---
# Debian-specific tasks

  
- name: Install XBMC repo
  sudo: Yes
  apt_repository: repo=ppa:team-xbmc/ppa

- name: Install update
  sudo: Yes
  command: apt-get update

- name: Install KODI
  apt: name=kodi state=present

- name: " Setup | apt | ensure added repos"
  sudo: Yes
  apt_repository: repo={{ kodi_pkg_apt_repo }}

